"""add unique exam question order

Revision ID: 0d84a2eabdc7
Revises: 598faf492f46
Create Date: 2026-09-28 09:45:13.905666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d84a2eabdc7'
down_revision: Union[str, Sequence[str], None] = '598faf492f46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_exam_question_order', 'exam_questions', ['exam_id', 'question_order'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_exam_question_order', 'exam_questions', type_='unique')
    # ### end Alembic commands ###
