"""create questions table

Revision ID: 1fc032997643
Revises: 2056e58fd573
Create Date: 2026-09-27 15:44:57.472149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fc032997643'
down_revision: Union[str, Sequence[str], None] = '2056e58fd573'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_exam_question', 'exam_questions', ['exam_id', 'question_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_exam_question', 'exam_questions', type_='unique')
    # ### end Alembic commands ###
