"""create question reviews table

Revision ID: 598faf492f46
Revises: f2cda95d2336
Create Date: 2026-09-27 20:11:52.532106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '598faf492f46'
down_revision: Union[str, Sequence[str], None] = 'f2cda95d2336'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_reviews_question_id'), 'question_reviews', ['question_id'], unique=False)
    op.create_index(op.f('ix_question_reviews_reviewer_id'), 'question_reviews', ['reviewer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_question_reviews_reviewer_id'), table_name='question_reviews')
    op.drop_index(op.f('ix_question_reviews_question_id'), table_name='question_reviews')
    op.drop_table('question_reviews')
    # ### end Alembic commands ###
