"""create batch members table

Revision ID: 7965b9646845
Revises: 9d0db6530701
Create Date: 2026-09-27 14:27:13.059989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7965b9646845'
down_revision: Union[str, Sequence[str], None] = '9d0db6530701'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batch_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_id', 'student_id', name='uq_batch_student')
    )
    op.create_index(op.f('ix_batch_members_batch_id'), 'batch_members', ['batch_id'], unique=False)
    op.create_index(op.f('ix_batch_members_student_id'), 'batch_members', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_batch_members_student_id'), table_name='batch_members')
    op.drop_index(op.f('ix_batch_members_batch_id'), table_name='batch_members')
    op.drop_table('batch_members')
    # ### end Alembic commands ###
