"""add exam completion target

Revision ID: 8019408fc160
Revises: 0d84a2eabdc7
Create Date: 2026-09-28 10:20:53.337649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8019408fc160'
down_revision: Union[str, Sequence[str], None] = '0d84a2eabdc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exams', sa.Column('completion_target', sa.Integer(), nullable=True))
    op.add_column('exams', sa.Column('auto_close_on_target', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exams', 'auto_close_on_target')
    op.drop_column('exams', 'completion_target')
    # ### end Alembic commands ###
