"""create exam examiners table

Revision ID: 857abb6d701e
Revises: 4d7ae6eb67cb
Create Date: 2026-09-27 15:15:10.311903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '857abb6d701e'
down_revision: Union[str, Sequence[str], None] = '4d7ae6eb67cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam_examiners',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('exam_id', sa.UUID(), nullable=False),
    sa.Column('examiner_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['examiner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exam_id', 'examiner_id', name='uq_exam_examiner')
    )
    op.create_index(op.f('ix_exam_examiners_exam_id'), 'exam_examiners', ['exam_id'], unique=False)
    op.create_index(op.f('ix_exam_examiners_examiner_id'), 'exam_examiners', ['examiner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exam_examiners_examiner_id'), table_name='exam_examiners')
    op.drop_index(op.f('ix_exam_examiners_exam_id'), table_name='exam_examiners')
    op.drop_table('exam_examiners')
    # ### end Alembic commands ###
