"""create exam batches table

Revision ID: 9bf796e20aae
Revises: 857abb6d701e
Create Date: 2026-09-27 15:17:01.872694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bf796e20aae'
down_revision: Union[str, Sequence[str], None] = '857abb6d701e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam_batches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('exam_id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exam_id', 'batch_id', name='uq_exam_batch')
    )
    op.create_index(op.f('ix_exam_batches_batch_id'), 'exam_batches', ['batch_id'], unique=False)
    op.create_index(op.f('ix_exam_batches_exam_id'), 'exam_batches', ['exam_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exam_batches_exam_id'), table_name='exam_batches')
    op.drop_index(op.f('ix_exam_batches_batch_id'), table_name='exam_batches')
    op.drop_table('exam_batches')
    # ### end Alembic commands ###
